### ISSUE TITLE
如何单独启动wormhole前端页面

### ISSUE THREAD

**Issue by Facegle** [edp963/wormhole#1008]
请问如何只运行wormhole的前端页面啊。看到用的是react框架，但是进入项目的`/rider-webapp`目录以后使用`yarn start`命令启动会报如下错：
--------------------------------------------------------------
D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp>yarn start
yarn run v1.15.2
warning package.json: "dependencies" has dependency "cross-env" with range "3.1.3" that collides with a dependency in "devDependencies" of the same name with version "^3.1.3"
$ cross-env NODE_ENV=development node server
'cross-env' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by dlt1111** [comment]
改用npm start。

**Comment by Facegle** [comment]
> 改用npm start。

谢谢。还是会报错
--------------------------------------
> rider-webapp@3.3.3 start D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp
> cross-env NODE_ENV=development node server

'cross-env' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rider-webapp@3.3.3 start: `cross-env NODE_ENV=development node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rider-webapp@3.3.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2019-05-09T04_30_40_182Z-debug.log

**Comment by dlt1111** [comment]
看样子是依赖包的问题，你试试把node_modules包删除，然后重新npm install一下， 安装完以后npm start启动试试。

**Comment by Facegle** [comment]
**谢谢。好像还是报错。我准备重新下载一个在试试。在这之前想请问，`npm start`命令是在`wormhole-0.6.1\rider\rider-webapp`下面执行对吗？**
报错信息如下：
npm ERR! code ETARGET
npm ERR! notarget No matching version found for tunnel-agent@0.6.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'pngquant-bin'
npm ERR! notarget
npm WARN tar ENOENT: no such file or directory, open 'D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp\node_modules\.staging\less-5b76a226\test\css\postProcessorPlugin\postProcessor.css'
npm WARN tar ENOENT: no such file or directory, lstat 'D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp\node_modules\.staging\less-5b76a226\test\css\preProcessorPlugin'
npm WARN tar ENOENT: no such file or directory, open 'D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp\node_modules\.staging\less-5b76a226\test\css\property-name-interp.css'
npm WARN tar ENOENT: no such file or directory, open 'D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp\node_modules\.staging\less-5b76a226\test\css\rulesets.css'
npm WARN tar ENOENT: no such file or directory, open 'D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp\node_modules\.staging\less-5b76a226\test\css\scope.css'
npm WARN tar ENOENT: no such file or directory, open 'D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp\node_modules\.staging\less-5b76a226\test\css\selectors.css'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2019-05-09T06_05_43_590Z-debug.log

**Comment by dlt1111** [comment]
> **谢谢。好像还是报错。我准备重新下载一个在试试。在这之前想请问，`npm start`命令是在`wormhole-0.6.1\rider\rider-webapp`下面执行对吗？**
> 报错信息如下：
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for tunnel-agent@0.6.1
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> npm ERR! notarget
> npm ERR! notarget It was specified as a dependency of 'pngquant-bin'
> npm ERR! notarget
> npm WARN tar ENOENT: no such file or directory, open 'D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp\node_modules.staging\less-5b76a226\test\css\postProcessorPlugin\postProcessor.css'
> npm WARN tar ENOENT: no such file or directory, lstat 'D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp\node_modules.staging\less-5b76a226\test\css\preProcessorPlugin'
> npm WARN tar ENOENT: no such file or directory, open 'D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp\node_modules.staging\less-5b76a226\test\css\property-name-interp.css'
> npm WARN tar ENOENT: no such file or directory, open 'D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp\node_modules.staging\less-5b76a226\test\css\rulesets.css'
> npm WARN tar ENOENT: no such file or directory, open 'D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp\node_modules.staging\less-5b76a226\test\css\scope.css'
> npm WARN tar ENOENT: no such file or directory, open 'D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp\node_modules.staging\less-5b76a226\test\css\selectors.css'
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\lenovo\AppData\Roaming\npm-cache_logs\2019-05-09T06_05_43_590Z-debug.log

对的。 路经没问题。 问题应该是某些依赖包没下载下来，你可以尝试用国内的镜像比如taobao的源来下载，或者vpn等方式多试几次。

**Comment by Facegle** [comment]
刚才重新从GitHub拉的代码。
npm换成淘宝的镜像了,使用`npm get registry `命令输出的网址是淘宝镜像：`https://registry.npm.taobao.org/`
但是使用`npm start`报下面的错误。会不会跟我装的node.js的版本有关？
或者您方便吧您现在在用的wormhole前端的源码发我一份吗。。

D:\temp\wormhole-master\rider\rider-webapp>npm start

 rider-webapp@3.3.3 start D:\temp\wormhole-master\rider\rider-webapp
 cross-env NODE_ENV=development node server

'cross-env' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rider-webapp@3.3.3 start: `cross-env NODE_ENV=development node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rider-webapp@3.3.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2019-05-09T06_49_34_542Z-debug.log

**Comment by Facegle** [comment]
> > **谢谢。好像还是报错。我准备重新下载一个在试试。在这之前想请问，`npm start`命令是在`wormhole-0.6.1\rider\rider-webapp`下面执行对吗？**
> > 报错信息如下：
> > npm ERR! code ETARGET
> > npm ERR! notarget No matching version found for tunnel-agent@0.6.1
> > npm ERR! notarget In most cases you or one of your dependencies are requesting
> > npm ERR! notarget a package version that doesn't exist.
> > npm ERR! notarget
> > npm ERR! notarget It was specified as a dependency of 'pngquant-bin'
> > npm ERR! notarget
> > npm WARN tar ENOENT: no such file or directory, open 'D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp\node_modules.staging\less-5b76a226\test\css\postProcessorPlugin\postProcessor.css'
> > npm WARN tar ENOENT: no such file or directory, lstat 'D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp\node_modules.staging\less-5b76a226\test\css\preProcessorPlugin'
> > npm WARN tar ENOENT: no such file or directory, open 'D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp\node_modules.staging\less-5b76a226\test\css\property-name-interp.css'
> > npm WARN tar ENOENT: no such file or directory, open 'D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp\node_modules.staging\less-5b76a226\test\css\rulesets.css'
> > npm WARN tar ENOENT: no such file or directory, open 'D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp\node_modules.staging\less-5b76a226\test\css\scope.css'
> > npm WARN tar ENOENT: no such file or directory, open 'D:\HaiYiWorkspace\wormhole-0.6.1\rider\rider-webapp\node_modules.staging\less-5b76a226\test\css\selectors.css'
> > npm ERR! A complete log of this run can be found in:
> > npm ERR! C:\Users\lenovo\AppData\Roaming\npm-cache_logs\2019-05-09T06_05_43_590Z-debug.log
> 
> 对的。 路经没问题。 问题应该是某些依赖包没下载下来，你可以尝试用国内的镜像比如taobao的源来下载，或者vpn等方式多试几次。

刚才重新从GitHub拉的代码。
npm换成淘宝的镜像了,使用npm get registry 命令输出的网址是淘宝镜像：https://registry.npm.taobao.org/
但是使用npm start报下面的错误。会不会跟我装的node.js的版本有关？
或者您方便吧您现在在用的wormhole前端的源码发我一份吗。。

D:\temp\wormhole-master\rider\rider-webapp>npm start

rider-webapp@3.3.3 start D:\temp\wormhole-master\rider\rider-webapp
cross-env NODE_ENV=development node server

'cross-env' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rider-webapp@3.3.3 start: cross-env NODE_ENV=development node server
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rider-webapp@3.3.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\lenovo\AppData\Roaming\npm-cache_logs\2019-05-09T06_49_34_542Z-debug.log

**Comment by dlt1111** [comment]
链接：https://share.weiyun.com/5fwLtlY 密码：hgy9yf

**Comment by Facegle** [comment]
> 链接：https://share.weiyun.com/5fwLtlY 密码：hgy9yf

好的谢谢哥，十分感谢！

**Comment by Facegle** [comment]
> 链接：https://share.weiyun.com/5fwLtlY 密码：hgy9yf

哥，启动成功了后台然后出来了url
D:\temp\wormhole-master\rider\rider-webapp>npm start

> rider-webapp@3.3.3 start D:\temp\wormhole-master\rider\rider-webapp
> cross-env NODE_ENV=development node server

Server started ✓

Access URLs:
- ----------------------------------
Localhost: http://localhost:8100
      LAN: http://192.168.29.1:8100
- ----------------------------------
Press CTRL-C to stop

但是浏览器打开以后只提示了一个not found，怎么办啊。。

**Comment by dlt1111** [comment]
not found？ 麻烦截个图, 带上地址栏。

**Comment by Facegle** [comment]
> not found？ 麻烦截个图, 带上地址栏。
不知道怎么放图。。浏览器not found 是因为后台报错的。错误信息有很多。主要内容是`'D:\temp\wormhole-master\rider\rider-webapp\node_modules\pngquant-bin\vendor\pngquant.exe' is not recognized as an internal or external command,`。百度和google都没有找到原因。。我看了一下对应目录没有可执行文件，只有一个pngquant文件（确定是这样的，我电脑设置的是可以显示文件扩展名的）

**Comment by Facegle** [comment]
![image](https://user-images.githubusercontent.com/29630372/57441082-c5684680-727b-11e9-8a72-53b4b0a6007c.png)
报错原因是这样的。
not found是这样的
![image](https://user-images.githubusercontent.com/29630372/57441114-d87b1680-727b-11e9-8fb9-2de8ff85fd02.png)

**Comment by dlt1111** [comment]
> > not found？ 麻烦截个图, 带上地址栏。
> > 不知道怎么放图。。浏览器not found 是因为后台报错的。错误信息有很多。主要内容是`'D:\temp\wormhole-master\rider\rider-webapp\node_modules\pngquant-bin\vendor\pngquant.exe' is not recognized as an internal or external command,`。百度和google都没有找到原因。。我看了一下对应目录没有可执行文件，只有一个pngquant文件（确定是这样的，我电脑设置的是可以显示文件扩展名的）

链接：https://share.weiyun.com/5cvZmA3 密码：argpw5
这个是 window的包， 刚才给你的是 mac 的 。 你用这个试试。

**Comment by Facegle** [comment]
> > > not found？ 麻烦截个图, 带上地址栏。
> > > 不知道怎么放图。。浏览器not found 是因为后台报错的。错误信息有很多。主要内容是`'D:\temp\wormhole-master\rider\rider-webapp\node_modules\pngquant-bin\vendor\pngquant.exe' is not recognized as an internal or external command,`。百度和google都没有找到原因。。我看了一下对应目录没有可执行文件，只有一个pngquant文件（确定是这样的，我电脑设置的是可以显示文件扩展名的）
> 
> 链接：https://share.weiyun.com/5cvZmA3 密码：argpw5
> 这个是 window的包， 刚才给你的是 mac 的 。 你用这个试试。

谢谢哥！！！能跑起来了！但是有一个问题，只启动前端我需要怎么进到主页面中啊。。在这个登陆页面进不去了。。
![image](https://user-images.githubusercontent.com/29630372/57495402-84fedc00-7300-11e9-9b71-5e1c321e0d71.png)

**Comment by dlt1111** [comment]
app文件下的index.html文件， 里面的 _RIDER_PRODUCTION_HOST值 改成你们服务的地址。

**Comment by Facegle** [comment]
> app文件下的index.html文件， 里面的 _RIDER_PRODUCTION_HOST值 改成你们服务的地址。

谢谢。我直接输网址可以进去。但是只能显示一部分，上面的导航条没有
![image](https://user-images.githubusercontent.com/29630372/57506106-6236ec80-732d-11e9-9f29-fea36f22259c.png)。
我在本机运行的需要连接数据库吗？不连可以吗（我可以先不关注表格中的内容，）。不连数据库的话， `_RIDER_PRODUCTION_HOST = `${location.origin}/api/v1`改成`localhost:8100/api/vl`吗

**Comment by dlt1111** [comment]
项目不是已经运行起来了么。页面的渲染大部分都是依赖数据的，没有数据的话部分页面就无法展示。

**Comment by dlt1111** [comment]
下面是前端页面的node_modules依赖包，方便下载依赖包失败的同学使用。

========= mac =========
链接：https://pan.baidu.com/s/1aIs594TYVqj1XWcUjelW1A 
提取码：6gmq 

========= win =========
链接：https://pan.baidu.com/s/1X3eF-2Qh1ai_6XmsJ_tRZQ 
提取码：w9bi

**Comment by dlt1111** [comment]
该issue已关闭，如有其他问题请另开issue!
