### ISSUE TITLE
新建UDF的时候需要的那个jar包里面写什么？有例子看一下嘛

### ISSUE THREAD

**Issue by lynchlee** [edp963/wormhole#327]
README里面提供的手册，不太详细，求一个详细一点的。
今天把wormhole跑起来来了。但是登陆进去后在流程上确实不太好理解，比如从哪里入手，要先设置什么，后设置什么，这个完全不懂。
比如说要新建一个UDF，但是我不知道那个Full class name和jar name是从哪里来的，是让用户上传一个？但是上传的入口在哪儿呢？或者wormhole需要和别的什么东西搭配使用？

多谢多谢。

**Comment by lynchlee** [comment]
能给一个小例子的实施流程那就很赞了。期待

**Comment by lynchlee** [comment]
@fumiwork

**Comment by swallowjy** [comment]
@lynchlee UDF有公有、私有两种类型，所有Project都可以访问公有UDF，私有UDF需要Admin授权。

Admin配置UDF时，需首先将UDF jar包上传到application.conf中spark.wormhole.hdfs.root.path配置项对应hdfs目录下的/udfjars目录下。

新建UDF，输入方法名，类名，jar包名称，保存时会检查hdfs目录上是否存在该jar包，不存在则无法新建成功。

**Comment by lynchlee** [comment]
@swallowjy  这个被上传到udfjars的jar包例子可以提供一个吗，这个jar包实现什么？

不好意思哈，我主要是想快速的把这个环境跑起来，前几天已经部署好了，但是目前还没跑起具体的业务例子，比如说跑一个计算PV/UV的例子啥的。

因为时间不多，所以没有去研究咱们里面怎么实现，纯属作为一个用户来使用咱们这个产品。

问题多了还望谅解哈。
