### ISSUE TITLE
[mad]模块研发

### ISSUE THREAD

**Issue by fumiwork** [edp963/wormhole#4]
支持默认feedback走数据库而非es，支持自己的监控线图展示，es/grafana成为可选项而非必须依赖项

**Comment by fumiwork** [comment]
考虑将［监控］作为独立于rider的定级服务模块，部署与否是可选的，如果不部署并且rider上不配置，即使用mysql和自带ui进行短时间窗口监控。如果部署并在rider上配置整合，则可利用es作为feedback存储（可存放更长时间窗口数据），同时监控模块支持可选的spark/wh日志归集过滤存储搜索服务。

如果自带监控ui完全满足需求，可考虑彻底不依赖grafana。

**Comment by 85016910** [comment]
去掉mad模块，将mad的监控融入到rider，主要在rider上增加flow和stream的监控相关展示
