### ISSUE TITLE
启动Stream后其状态一直处于starting  , 且Flow启动后状态一直为suspending

### ISSUE THREAD

**Issue by xiaoyiSantos** [edp963/wormhole#593]
jdk 1.8
wormhole 0.4.1
Linux version 3.10.0-693.17.1.el7.x86_64

在尝试文档中QuickStart中的Demo时 , 发现启动Stream后其状态一直处于starting  , 且Flow启动后status从starting立即变为suspending

![image](https://user-images.githubusercontent.com/39982368/41022505-61938036-699c-11e8-8b12-253444aeb88d.png)

![image](https://user-images.githubusercontent.com/39982368/41022546-81225b70-699c-11e8-93fb-a0a7cbf8ac2a.png)

**Comment by swallowjy** [comment]
@xiaoyiSantos 一般情况下这种原因是因为spark部署问题，wormhole spark配置路径问题或启动用户问题，看下stream后面的日志，有没有错误信息提示。没有的话对照下部署文档，然后数据库将stream状态改为failed。另外推荐自己编译master分支代码，修复了很多bug，下周会发布个新版本，谢谢～～

**Comment by xiaoyiSantos** [comment]
@swallowjy 谢谢回复! ! 
1. 查看stream后的日志,内容为"The stream log/job file doesn't exist." ; 
2. 另外您回复的 "然后数据库将stream状态改为failed......" 这句话不太明白什么意思 ; 
3. 配置文件中

**Comment by swallowjy** [comment]
@xiaoyiSantos 应该是配置有问题，请根据部署文档检查一下你的安装过程~~

https://edp963.github.io/wormhole/deployment.html

**Comment by xiaoyiSantos** [comment]
@swallowjy 您好， 我检查了安装过程并没有出现问题，Spark 和 Yarn也都正常运行。wormhole也是正常启动，在启动过程中也没有报错。另外，我想问下，您说的这周发布新版本大概是周几呢？谢谢回复！

**Comment by swallowjy** [comment]
@xiaoyiSantos 周二，明天换新版本试试哈~~

可以扫描文档上的二维码加入用户群，方便及时沟通~~

**Comment by xiaoyiSantos** [comment]
@swallowjy 好的好的已经加入，谢谢回复！
