### ISSUE TITLE
离线任务

### ISSUE THREAD

**Issue by Sinmes** [edp963/wormhole#77]
我在代码里看到有离线job，但UI没找到，是没有开放吗？  有开放时间吗？

**Comment by swallowjy** [comment]
app rest api 有提供三方调用接口，UI还未添加。目前离线job数据源只支持wormhole hdfslog stream同步至hdfs上的数据。你们对离线job的需求可以具体描述下。

**Comment by Sinmes** [comment]
@swallowjy 
我们对离线job的需求为：脚本定时调用rest，拉取Oracle表指时间段数据（不知道能否用DBUS实现），经过Transformation（LookUp SQL，SparkSQL，自定义class），输出结果（多种Sink）。

**Comment by swallowjy** [comment]
@Sinmes 
作业调度建议用专业开源工具如azkaban/airflow等，这个超出wh定位；Wormhole直接支持多数据源也超出定位，可以先使用DBUS获取数据库的变更，再通过Wormhole hdfslog stream 生成hdfslog文件；transformation和多输出目标幂等入库已支持。

**Comment by Sinmes** [comment]
OK，目前数据源只支持通过Wormhole hdfslog stream 生成的hdfslog文件是吗？    UI有添加的计划吗？   另外建议完善一下文档：），很看好这个项目。

**Comment by swallowjy** [comment]
@Sinmes 感谢建议与支持，Job UI 计划12月份开发，可以关注我们目前的开发计划，https://github.com/edp963/wormhole/projects/1 。

**Comment by swallowjy** [comment]
@Sinmes 可以扫描首页的微信二维码，加入wormhole开源讨论群，可了解最新动态，方便沟通~~
