### ISSUE TITLE
[flinkx]flink streaming支持

### ISSUE THREAD

**Issue by fumiwork** [edp963/wormhole#9]
低优先级，等待flink更加成熟

**Comment by 85016910** [comment]
准备开发，主要支持sql和cep，sink只支持kafka

**Comment by 85016910** [comment]
已确定方案，计划6月30日出第一版，支持flink sql和cep配置

**Comment by sunsence** [comment]
已完成pattern定义中的where条件解析，预计2周内完成其他功能代码编写

**Comment by sunsence** [comment]
pattern定义整体流程串通，已完成此模块本地测试。预计下周完成整体流程串通

**Comment by sunsence** [comment]
解决动态绑定stream type问题，整体流程串通。下周确定如何设置event time，precessing time，如何交叉配置sql和pattern，以及校验代码流程。

**Comment by sunsence** [comment]
支持定义多组pattern，增加pattern输出配置。下周解决数据schema变更的问题以及手动提交Job验证整体流程。

**Comment by sunsence** [comment]
解决了schema变更问题；确定配置文件及directive_flow_start的定义；增加key by功能。下周解决table与datastream转换问题。

**Comment by sunsence** [comment]
完成key by 功能及set time characteristic功能。待解决问题，测试环境flink搭建及lookup sql 、flink sql 、及pattern的交叉定义及解析

**Comment by swallowjy** [comment]
这周确定了与flinkx相关的stream/flow接口，预计11个工作日开发完成。目前小海已经开始开发stream部分接口。

**Comment by 85016910** [comment]
[rider+ui]已完成streaming相关管理功能开发，[flinkx]已完成框架、sql、cep相关功能开发

**Comment by 85016910** [comment]
[rider+ui]已经完成flow相关管理功能开发（除cep配置功能），[flinkx]已完成此版本功能开发，开始测试
