### ISSUE TITLE
[kafka]在database中写了kafka的config，为什么提交过去的任务client.id和group.id还是错的？

### ISSUE THREAD

**Issue by vicviz** [edp963/wormhole#990]
config中

![image](https://user-images.githubusercontent.com/2442699/57203657-8371a300-6fe4-11e9-9c81-6f29b7a1e463.png)

但提交后的flink任务日志如下，client.id是空的，group.id是错的

       client.id = 
	connections.max.idle.ms = 540000
	enable.auto.commit = true
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = kafka.mynamespace.rt.action.*.*.*-mysql.test.sink.user.*.*.*

**Comment by swallowjy** [comment]
有些数据库类型的config加到对应connection config中了，有些没加，但也都是在sink层面。你想要加flink kafka consumer的配置是吗？group.id不需要自己设，rider-server里有设置，cluster_id-sourceNs-sinkNs，其他项的配置没有支持用户自定义，我们看着怎么加下~~

**Comment by swallowjy** [comment]
目前没有计划支持该功能~~
